crds:
  enabled: true

global:
  commonLabels:
    tags.datadoghq.com/source: cert-manager

webhook:
  serviceAnnotations:
    # IST0118: Port name 'metrics' doesn't follow Istio naming convention.
    # The chart doesn't support customizing port names, so we suppress the warning.
    galley.istio.io/analyze-suppress: IST0118
