name: OpenTofu Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    uses: osinfra-io/pt-techne-opentofu-workflows/.github/workflows/test.yml@5e0e5ea22c629ef678da26c0cecf640f56c15653 # v0.3.1
    if: github.actor != 'dependabot[bot]'
    with:
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
